# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gC8tWowdB8-lVgPKtwm-ldAo87u-bV5_
"""

import matplotlib.pyplot as plt
import numpy as np

x=np.array([4,6,10,15])
y=np.array([0,5,1,3])


plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
y=np.array([0, 0.5, 0, -1, 0, 1.5, 0, -0.5, 0, 0.2, 0])


plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([1,2,3,4,5,6,7])
y=np.array([1,8,16,32,64,128,256])


plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np


y=np.array([3,9,1,8])


plt.plot(y, 'o:g')
plt.show()

import matplotlib.pyplot as plt
import numpy as np


y=np.array([3,9,5,8])


plt.pie(y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np


y=np.array([3,9,5,8])
x=np.array([8,2,4,3])
y2=np.array([3,9,5,8])
x2=np.array([2,9,4,7])


plt.plot(y,x,y2,x2)
plt.show()

import matplotlib.pyplot as plt
import numpy as np


y=np.array([3,9,5,8])
x=np.array([8,2,4,3])
y2=np.array([3,9,5,8])
x2=np.array([2,9,4,7])


plt.plot(y,x,y2,x2)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([4,6,10,15])
y=np.array([0,5,1,3])


plt.scatter(x,y,color='yellow')

x=np.array([3,7,32,56])
y=np.array([43,6,23,45])


plt.scatter(x,y,color='blue')

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array(['A','B','C','D'])
y=np.array([2,5,1,3])


plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array(['A','B','C','D'])
y=np.array([2,5,1,3])


plt.barh(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np


y=np.array([3,9,5,8])
mylabels= ['bugatata', 'rozirozi', 'lambargambar', 'fririri']


plt.pie(y, labels=mylabels)
plt.show()

import matplotlib.pyplot as plt
import numpy as np


y=np.array([3,9,5,8])
mylabels= ['bugatata', 'rozirozi', 'lambargambar', 'fririri']
myexplode= [0.4, 0,0,0]

plt.pie(y, labels=mylabels, explode=myexplode)
plt.show()

import matplotlib.pyplot as plt
import numpy as np


y=np.array([3,9,5,8])
mylabels= ['bugatata', 'rozirozi', 'lambargambar', 'fririri']
myexplode= [0.4, 0,0,0]

plt.pie(y, labels=mylabels, explode=myexplode, shadow=True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np


y=np.array([3,9,5,8])
mylabels= ['bugatata', 'rozirozi', 'lambargambar', 'fririri']
myexplode= [0.4, 0,0,0]

plt.pie(y, labels=mylabels, explode=myexplode, shadow=True)
plt.legend(title='Cars:')
plt.show()